[project]
name = "building-an-interactive-data-app-using-python-and-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.5.1",
    "streamlit>=1.52.2",
]
